const searchBox = document.getElementById("searchBox");
  
  const suggestions = [
    "Weather today",
    "Latest news",
    "YouTube",
    "Google Maps",
    "Wikipedia",
    "Translate",
    "Cricket news",
    "Movies near me",
    "Stock market today",
    "Today's football match",
"Lionel Messi",
"Cristiano Ronaldo",
"Neymar Jr",
"Kylian Mbappé",
"Erling Haaland",
"Lamine Yamal",
"Jude Bellingham",
"Vinícius Júnior",
"Rodrygo",
"Federico Valverde",
"Luka Modrić",
"Toni Kroos",
"Eduardo Camavinga",
"Aurélien Tchouaméni",
"Thibaut Courtois",
"Dani Carvajal",
"Antonio Rüdiger",
"Éder Militão",
"David Alaba",
"Ferland Mendy",
"Robert Lewandowski",
"Pedri",
"Gavi",
"Frenkie de Jong",
"Raphinha",
"Ronald Araújo",
"Jules Koundé",
"Marc-André ter Stegen",
"João Félix",
"Ansu Fati",
"Alejandro Balde",
"Ferran Torres",
"Mohamed Salah",
"Kevin De Bruyne",
"Phil Foden",
"Jack Grealish",
"Bernardo Silva",
"Jérémy Doku",
"Rúben Dias",
"John Stones",
"Kyle Walker",
"Ederson",
"Harry Kane",
"Son Heung-min",
"Bukayo Saka",
"Martin Ødegaard",
"Declan Rice",
"Kai Havertz",
"Gabriel Martinelli",
"William Saliba",
"Gabriel Magalhães",
"Bruno Fernandes",
"Marcus Rashford",
"Casemiro",
"André Onana",
"Lisandro Martínez",
"Mason Mount",
"Alejandro Garnacho",
"Kobbie Mainoo",
"Virgil van Dijk",
"Alisson Becker",
"Trent Alexander-Arnold",
"Andrew Robertson",
"Alexis Mac Allister",
"Dominik Szoboszlai",
"Luis Díaz",
"Darwin Núñez",
"Cole Palmer",
"Enzo Fernández",
"Reece James",
"Christopher Nkunku",
"Nicolas Jackson",
"Enzo Maresca",
"Victor Osimhen",
"Khvicha Kvaratskhelia",
"Lautaro Martínez",
"Marcus Thuram",
"Hakan Çalhanoğlu",
"Nicolò Barella",
"Rafael Leão",
"Theo Hernández",
"Mike Maignan",
"Dusan Vlahović",
"Federico Chiesa",
"Adrien Rabiot",
"Gianluigi Donnarumma",
"Ousmane Dembélé",
"Achraf Hakimi",
"Marquinhos",
"Warren Zaïre-Emery",
"Gonçalo Ramos",
"João Neves",
"Cristian Romero",
"Emiliano Martínez",
"Julian Álvarez",
"Alexis Mac Allister",
"Enzo Fernández",
"Paulo Dybala",
"Ángel Di María",
"Lisandro Martínez",
"Emiliano Buendía",
"Lautaro Martínez",
"Romelu Lukaku",
"Kevin De Bruyne",
"Leandro Trossard",
"Jérémy Doku",
"Youri Tielemans",
"Thibaut Courtois",
"Alphonso Davies",
"Jamal Musiala",
"Florian Wirtz",
"Joshua Kimmich",
"Manuel Neuer",
"Thomas Müller",
"Leroy Sané",
"Serge Gnabry",
"Kai Havertz",
"Niclas Füllkrug",
"Ilkay Gündoğan",
"Joško Gvardiol",
"Dominik Livaković",
"Luka Sučić",
"Josip Šutalo",
"Andrej Kramarić",
"Ivan Perišić",
"Modrić",
"Ronaldo Nazário",
"Ronaldinho",
"Kaká",
"Pelé",
"Diego Maradona",
"Zinedine Zidane",
"Andrés Iniesta",
"Xavi",
"Sergio Ramos",
"Gerard Piqué",
"David Beckham",
"Wayne Rooney",
"Paul Scholes",
"Ryan Giggs",
"Frank Lampard",
"Steven Gerrard",
"Didier Drogba",
"Thierry Henry",
"Patrick Vieira",
"Rio Ferdinand",
"Nemanja Vidić",
"Iker Casillas",
"Carles Puyol",
"Luis Suárez",
"Edinson Cavani",
"Gareth Bale",
"Eden Hazard",
"Mesut Özil",
"Arjen Robben",
"Franck Ribéry",
"Bastian Schweinsteiger",
"Robin van Persie",
"Ruud van Nistelrooy",
"Ruud Gullit",
"Marco van Basten",
"George Best",
"Johan Cruyff",
"Paolo Maldini",
"Andrea Pirlo",
"Francesco Totti",
"Alessandro Del Piero",
"Gianluigi Buffon",
"Fabio Cannavaro",
"Roberto Carlos",
"Cafu",
"Rivaldo",
"Romário",
"Rivaldo",
"Samuel Eto'o",
"Yaya Touré",
"Didier Drogba",
"Sadio Mané",
"Riyad Mahrez",
"Hakim Ziyech",
"Achraf Hakimi",
"Victor Boniface",
"Victor Osimhen",
"Manchester United",
"Manchester City",
"Liverpool",
"Chelsea",
"Arsenal",
"Tottenham Hotspur",
"Newcastle United",
"Aston Villa",
"Everton",
"West Ham United",
"Brighton",
"Wolverhampton Wanderers",
"Nottingham Forest",
"Leicester City",
"Leeds United",
"Fulham",
"Crystal Palace",
"Brentford",
"Burnley",
"Bournemouth",
"Real Madrid",
"Barcelona",
"Atlético Madrid",
"Sevilla",
"Valencia",
"Villarreal",
"Real Sociedad",
"Athletic Bilbao",
"Real Betis",
"Getafe",
"Girona",
"Espanyol",
"Osasuna",
"Celta Vigo",
"Rayo Vallecano",
"Mallorca",
"Bayern Munich",
"Borussia Dortmund",
"Bayer Leverkusen",
"RB Leipzig",
"Eintracht Frankfurt",
"VfB Stuttgart",
"Wolfsburg",
"Borussia Mönchengladbach",
"Werder Bremen",
"SC Freiburg",
"Hoffenheim",
"Mainz 05",
"FC Köln",
"Hamburg SV",
"Juventus",
"Inter Milan",
"AC Milan",
"Napoli",
"Roma",
"Lazio",
"Atalanta",
"Fiorentina",
"Bologna",
"Torino",
"Parma",
"Udinese",
"Sampdoria",
"Genoa",
"Paris Saint-Germain",
"Marseille",
"Lyon",
"Monaco",
"Lille",
"Nice",
"Lens",
"Rennes",
"Nantes",
"Montpellier",
"Ajax",
"PSV Eindhoven",
"Feyenoord",
"Benfica",
"Sporting CP",
"FC Porto",
"Galatasaray",
"Fenerbahçe",
"Beşiktaş",
"Celtic",
"Rangers",
"Club Brugge",
"Shakhtar Donetsk",
"Red Star Belgrade",
"Dinamo Zagreb",
"Al Nassr",
"Al Hilal",
"Al Ahli",
"Al Ittihad",
"Inter Miami",
"LA Galaxy",
"Los Angeles FC",
"New York City FC",
"Brazil",
"Argentina",
"Spain",
"France",
"Germany",
"England",
"Portugal",
"Italy",
"Netherlands",
"Belgium",
"Croatia",
"Uruguay",
"Colombia",
"Mexico",
"Japan",
"South Korea",
"Morocco",
"Nigeria",
"Senegal",
"Egypt",
"United States",
"Canada",
"Australia",
"Switzerland",
"Denmark",
"Sweden",
"Norway",
"Poland",
"Serbia",
"Türkiye",
"India Football Team",
"Kerala Blasters",
"Mohun Bagan",
"Bengaluru FC",
"Mumbai City FC",
"FC Goa",
"East Bengal",
"Chennaiyin FC",
"Indian Super League",
"Premier League",
"La Liga",
"Serie A",
"Bundesliga",
"Ligue 1",
"UEFA Champions League",
"Europa League",
"FIFA World Cup",
"UEFA Euro",
"Copa America",
"Club World Cup",
"Virat Kohli",
"MS Dhoni",
"Rohit Sharma",
"Sachin Tendulkar",
"Jasprit Bumrah",
"Hardik Pandya",
"KL Rahul",
"Shubman Gill",
"Rishabh Pant",
"Suryakumar Yadav",
"Yashasvi Jaiswal",
"Mohammed Shami",
"Mohammed Siraj",
"Ravindra Jadeja",
"Ravichandran Ashwin",
"Kuldeep Yadav",
"Axar Patel",
"Ishan Kishan",
"Sanju Samson",
"Shreyas Iyer",
"Tilak Varma",
"Washington Sundar",
"Arshdeep Singh",
"Prasidh Krishna",
"Nitish Kumar Reddy",
"Abhishek Sharma",
"Ruturaj Gaikwad",
"Rahul Dravid",
"Gautam Gambhir",
"Anil Kumble",
"Harbhajan Singh",
"Yuvraj Singh",
"Virender Sehwag",
"Sourav Ganguly",
"VVS Laxman",
"Cheteshwar Pujara",
"Ajinkya Rahane",
"Zaheer Khan",
"Irfan Pathan",
"Yusuf Pathan",
"Robin Uthappa",
"Dinesh Karthik",
"Bhuvneshwar Kumar",
"Deepak Chahar",
"Shardul Thakur",
"Mayank Agarwal",
"Prithvi Shaw",
"Ravichandran Ashwin",
"Ravindra Jadeja",
"Pat Cummins",
"Mitchell Starc",
"Josh Hazlewood",
"Steve Smith",
"David Warner",
"Travis Head",
"Glenn Maxwell",
"Marnus Labuschagne",
"Alex Carey",
"Cameron Green",
"Mitchell Marsh",
"Nathan Lyon",
"Adam Zampa",
"Usman Khawaja",
"Shaun Marsh",
"Aaron Finch",
"Michael Clarke",
"Ricky Ponting",
"Shane Watson",
"Shane Warne",
"Brett Lee",
"Adam Gilchrist",
"Matthew Hayden",
"Kane Williamson",
"Trent Boult",
"Tim Southee",
"Devon Conway",
"Rachin Ravindra",
"Daryl Mitchell",
"Tom Latham",
"Lockie Ferguson",
"Ross Taylor",
"Martin Guptill",
"Babar Azam",
"Mohammad Rizwan",
"Shaheen Afridi",
"Haris Rauf",
"Fakhar Zaman",
"Naseem Shah",
"Imam-ul-Haq",
"Abdullah Shafique",
"Shadab Khan",
"Wasim Akram",
"Waqar Younis",
"Inzamam-ul-Haq",
"Saeed Anwar",
"Shoaib Akhtar",
"Brian Lara",
"Chris Gayle",
"Andre Russell",
"Sunil Narine",
"Nicholas Pooran",
"Shimron Hetmyer",
"Jason Holder",
"Kieron Pollard",
"Dwayne Bravo",
"Carlos Brathwaite",
"Ben Stokes",
"Joe Root",
"Jos Buttler",
"Jofra Archer",
"Harry Brook",
"Jonny Bairstow",
"Mark Wood",
"Stuart Broad",
"James Anderson",
"Eoin Morgan",
"Alastair Cook",
"AB de Villiers",
"Quinton de Kock",
"Kagiso Rabada",
"Aiden Markram",
"Heinrich Klaasen",
"David Miller",
"Marco Jansen",
"Dale Steyn",
"Faf du Plessis",
"Hashim Amla",
"Sri Lanka",
"Bangladesh",
"Afghanistan",
"Ireland",
"Zimbabwe",
"England Cricket Team",
"Australia Cricket Team",
"Pakistan Cricket Team",
"New Zealand Cricket Team",
"South Africa Cricket Team",
"India Cricket Team",
"Royal Challengers Bengaluru",
"Chennai Super Kings",
"Mumbai Indians",
"Kolkata Knight Riders",
"Rajasthan Royals",
"Sunrisers Hyderabad",
"Delhi Capitals",
"Punjab Kings",
"Lucknow Super Giants",
"Gujarat Titans",
"Indian Premier League",
"IPL",
"T20 World Cup",
"Cricket World Cup",
"Champions Trophy",
"Avengers",
"Avengers Endgame",
"Avengers Infinity War",
"Avengers Age of Ultron",
"The Avengers",
"Captain America",
"Captain America Civil War",
"Captain America The Winter Soldier",
"Captain America The First Avenger",
"Iron Man",
"Iron Man 2",
"Iron Man 3",
"Thor",
"Thor Ragnarok",
"Thor Love and Thunder",
"Thor The Dark World",
"Doctor Strange",
"Doctor Strange in the Multiverse of Madness",
"Spider-Man",
"Spider-Man No Way Home",
"Spider-Man Far From Home",
"Spider-Man Homecoming",
"Spider-Man Across the Spider-Verse",
"Spider-Man Into the Spider-Verse",
"The Amazing Spider-Man",
"The Amazing Spider-Man 2",
"Spider-Man 2",
"Spider-Man 3",
"Black Panther",
"Black Panther Wakanda Forever",
"Black Widow",
"Hulk",
"The Incredible Hulk",
"Ant-Man",
"Ant-Man and the Wasp",
"Ant-Man and the Wasp Quantumania",
"Guardians of the Galaxy",
"Guardians of the Galaxy Vol. 2",
"Guardians of the Galaxy Vol. 3",
"Captain Marvel",
"The Marvels",
"Eternals",
"Shang-Chi",
"Deadpool",
"Deadpool 2",
"Deadpool and Wolverine",
"Wolverine",
"X-Men",
"Logan",
"Daredevil",
"Loki",
"WandaVision",
"Moon Knight",
"Hawkeye",
"Ms Marvel",
"She-Hulk",
"The Falcon and the Winter Soldier",
"What If",
"Fantastic Four",
"Fantastic Four First Steps",
"Doctor Doom",
"Galactus",
"Scarlet Witch",
"Vision",
"Thanos",
"Nick Fury",
"Black Bolt",
"Namor",
"Batman",
"The Batman",
"Batman Begins",
"The Dark Knight",
"The Dark Knight Rises",
"Superman",
"Superman Returns",
"Man of Steel",
"Superman Legacy",
"Wonder Woman",
"Aquaman",
"The Flash",
"Green Lantern",
"Justice League",
"Zack Snyder Justice League",
"Suicide Squad",
"The Suicide Squad",
"Black Adam",
"Blue Beetle",
"Shazam",
"Joker",
"The Joker",
"Harley Quinn",
"The Penguin",
"Peacemaker",
"Watchmen",
"Constantine",
"Avatar",
"Avatar The Way of Water",
"Titanic",
"Interstellar",
"Inception",
"Oppenheimer",
"Tenet",
"Dunkirk",
"The Prestige",
"The Dark Knight",
"John Wick",
"John Wick Chapter 2",
"John Wick Chapter 3",
"John Wick Chapter 4",
"Mission Impossible",
"Mission Impossible Dead Reckoning",
"Top Gun",
"Top Gun Maverick",
"Jurassic Park",
"Jurassic World",
"Fast and Furious",
"Fast Five",
"Furious 7",
"The Fate of the Furious",
"Fast X",
"The Matrix",
"The Matrix Reloaded",
"The Matrix Revolutions",
"Gladiator",
"Gladiator 2",
"Transformers",
"Bumblebee",
"King Kong",
"Godzilla",
"Godzilla x Kong",
"Pirates of the Caribbean",
"Harry Potter",
"Fantastic Beasts",
"The Lord of the Rings",
"The Hobbit",
"Star Wars",
"Rogue One",
"The Mandalorian",
"Dune",
"Dune Part Two",
"The Lion King",
"Frozen",
"shutter island",
"Moana",
"Finding Nemo",
"Toy Story",
"Cars",
"Coco",
"Inside Out",
"Minions",
"Despicable Me",
"Kung Fu Panda",
"How to Train Your Dragon",
"Shrek",
"Madagascar",
"Ice Age",
"Pushpa",
"Pushpa 2",
"Baahubali",
"Baahubali 2",
"RRR",
"Kalki 2898 AD",
"Salaar",
"KGF",
"KGF Chapter 2",
"Devara",
"Game Changer",
"OG",
"Hari Hara Veera Mallu",
"Spirit",
"The Raja Saab",
"Leo",
"Vikram",
"Master",
"Jailer",
"Beast",
"Thalapathy 69",
"Coolie",
"Thunivu",
"Valimai",
"Kaithi",
"Lokesh Cinematic Universe",
"Kantara",
"Kantara Chapter 1",
"777 Charlie",
"Martin",
"Sita Ramam",
"Hi Nanna",
"Lucky Baskhar",
"Good Bad Ugly",
"Empuraan",
"Lucifer",
"Drishyam",
"Drishyam 2",
"Neru",
"Aavesham",
"Premalu",
"Manjummel Boys",
"Bramayugam",
"ARM",
"2018",
"Kannur Squad",
"RDX",
"Marco",
"Thudarum",
"Odiyan",
"Pulimurugan",
"Oppam",
"Kurup",
"King of Kotha",
"Malik",
"Jana Gana Mana",
"Android Kunjappan",
"Romancham",
"Minnal Murali",
"Turbo",
"Mohanlal",
"Mammootty",
"Prithviraj Sukumaran",
"Dulquer Salmaan",
"Fahadh Faasil",
"Tovino Thomas",
"Nivin Pauly",
"Asif Ali",
"Kunchacko Boban",
"Unni Mukundan",
"Basil Joseph",
"Soubin Shahir",
"Shane Nigam",
"Naslen",
"Mathew Thomas",
"Vijay",
"Ajith Kumar",
"Suriya",
"Kamal Haasan",
"Rajinikanth",
"Sivakarthikeyan",
"Dhanush",
"Karthi",
"Silambarasan",
"Vijay Sethupathi",
"Prabhas",
"Allu Arjun",
"Ram Charan",
"Jr NTR",
"Mahesh Babu",
"Pawan Kalyan",
"Nani",
"Naga Chaitanya",
"Chiranjeevi",
"Balakrishna",
"Shah Rukh Khan",
"Salman Khan",
"Aamir Khan",
"Hrithik Roshan",
"Ranbir Kapoor",
"Ranveer Singh",
"Akshay Kumar",
"Ajay Devgn",
"Tiger Shroff",
"Kartik Aaryan",
"Amitabh Bachchan",
"Deepika Padukone",
"Alia Bhatt",
"Katrina Kaif",
"Kiara Advani",
"Kriti Sanon",
"Shraddha Kapoor",
"Jawan",
"Pathaan",
"Animal",
"Dangal",
"PK",
"3 Idiots",
"Bajrangi Bhaijaan",
"War",
"Fighter",
"Singham",
"Singham Again",
"Housefull",
"Golmaal",
"Bhool Bhulaiyaa",
"Stree",
"Stree 2",
"Chhaava",
"Breaking Bad",
"Better Call Saul",
"Stranger Things",
"Wednesday",
"Money Heist",
"Squid Game",
"Dark",
"The Boys",
"Gen V",
"The Last of Us",
"House of the Dragon",
"Game of Thrones",
"The Walking Dead",
"The Witcher",
"Peaky Blinders",
"Sherlock",
"Chernobyl",
"Prison Break",
"Dexter",
"You",
"Alice in Borderland",
"All of Us Are Dead",
"Kingdom",
"Narcos",
"Ozark",
"Reacher",
"Jack Ryan",
"The Night Agent",
"The Penguin",
"Daredevil Born Again",
"Loki Season 2",
"Moon Knight",
"WandaVision",
"Hawkeye",
"The Falcon and the Winter Soldier",
"What If",
"Ironheart",
"Vision Quest",
"The Punisher",
"Jessica Jones",
"Luke Cage",
"Iron Fist",
"The Defenders",
"One Piece Live Action",
"Avatar The Last Airbender",
"The Mandalorian",
"Andor",
"Obi-Wan Kenobi",
"Ahsoka",
"The Book of Boba Fett",
"The Office",
"Friends",
"How I Met Your Mother",
"Brooklyn Nine-Nine",
"The Big Bang Theory",
"Modern Family",
"Suits",
"House",
"Grey's Anatomy",
"Black Mirror",
"The Sandman",
"The Bear",
"Severance",
"Silo",
"From",
"Invincible",
"Arcane",
"Blue Eye Samurai",
"Solo Leveling",
"One Piece",
"Naruto",
"Naruto Shippuden",
"Boruto",
"Dragon Ball",
"Dragon Ball Z",
"Dragon Ball Super",
"Attack on Titan",
"Demon Slayer",
"Jujutsu Kaisen",
"Chainsaw Man",
"Bleach",
"Bleach Thousand-Year Blood War",
"Death Note",
"Hunter x Hunter",
"My Hero Academia",
"Black Clover",
"Haikyuu",
"Blue Lock",
"Spy x Family",
"Tokyo Revengers",
"Tokyo Ghoul",
"Fullmetal Alchemist Brotherhood",
"Code Geass",
"Steins Gate",
"Vinland Saga",
"Monster",
"JoJo's Bizarre Adventure",
"Fire Force",
"Mashle",
"Dr Stone",
"The Apothecary Diaries",
"Frieren",
"Kaiju No. 8",
"Wind Breaker",
"Classroom of the Elite",
"Re Zero",
"No Game No Life",
"Sword Art Online",
"Your Name",
"A Silent Voice",
"Spirited Away",
"Weathering With You",
"Suzume",
"Princess Mononoke",
"Howl's Moving Castle",
"Grave of the Fireflies",
"Studio Ghibli",
"Pokemon",
"Digimon",
"GTA 6",
"Grand Theft Auto V",
"Grand Theft Auto San Andreas",
"Minecraft",
"PUBG",
"BGMI",
"Free Fire",
"Call of Duty",
"Call of Duty Mobile",
"Valorant",
"Counter-Strike 2",
"Fortnite",
"Roblox",
"EA Sports FC 26",
"FIFA",
"eFootball",
"Rocket League",
"Clash of Clans",
"Clash Royale",
"Brawl Stars",
"Among Us",
"League of Legends",
"Dota 2",
"Apex Legends",
"Rainbow Six Siege",
"The Witcher 3",
"Red Dead Redemption 2",
"Elden Ring",
"God of War",
"God of War Ragnarok",
"Horizon Forbidden West",
"Ghost of Tsushima",
"Black Myth Wukong",
"Resident Evil 4",
"Resident Evil Village",
"Silent Hill 2",
"Assassin's Creed Shadows",
"Cyberpunk 2077",
"Marvel Rivals",
"World of Warcraft",
"Overwatch 2",
"Hollow Knight",
"Hades",
"Terraria",
"The Legend of Zelda",
"Super Mario Bros",
"Pokemon Legends Z-A",
"India",
"United States",
"United Kingdom",
"Canada",
"Australia",
"New Zealand",
"Germany",
"France",
"Italy",
"Spain",
"Portugal",
"Netherlands",
"Belgium",
"Switzerland",
"Austria",
"Norway",
"Sweden",
"Denmark",
"Finland",
"Ireland",
"Brazil",
"Argentina",
"Mexico",
"Japan",
"South Korea",
"China",
"Singapore",
"Malaysia",
"Thailand",
"Indonesia",
"UAE",
"Saudi Arabia",
"Qatar",
"South Africa",
"Kerala",
"Kochi",
"Thiruvananthapuram",
"Kozhikode",
"Thrissur",
"Kannur",
"Kottayam",
"Alappuzha",
"Munnar",
"Wayanad",
"Varkala",
"Bengaluru",
"Chennai",
"Hyderabad",
"Mumbai",
"Delhi",
"Kolkata",
"Goa",
"Dubai",
"London",
"Paris",
"New York",
"Los Angeles",
"Tokyo",
"Seoul",
"Singapore City",
"Sydney",
"Rome",
"Barcelona",
"Madrid",
"Amsterdam",
"Istanbul",
"Maldives",
"Bali",
"Switzerland Tour",
"Mount Everest",
"Taj Mahal",
"Burj Khalifa",
"Eiffel Tower",
"Big Ben",
"Statue of Liberty",
"Google News",
"Breaking News",
"Weather Today",
"Live Cricket Score",
"Football News",
"Champions League",
"Premier League Table",
"La Liga Table",
"IPL Points Table",
"World Cup",
"Olympics",
"Stock Market",
"Gold Price Today",
"Bitcoin Price",
"Ethereum Price",
"US Dollar to INR",
"AI News",
"ChatGPT",
"Google",
"YouTube",
"Instagram",
"Facebook",
"WhatsApp",
"X",
"Netflix",
"Amazon Prime Video",
"Disney Plus",
"Spotify",
"OpenAI",
// International Celebrities
"Leonardo DiCaprio",
"Robert Downey Jr.",
"Chris Hemsworth",
"Chris Evans",
"Chris Pratt",
"Tom Holland",
"Tom Hiddleston",
"Ryan Reynolds",
"Ryan Gosling",
"Dwayne Johnson",
"Jason Momoa",
"Jason Statham",
"Keanu Reeves",
"Brad Pitt",
"George Clooney",
"Johnny Depp",
"Will Smith",
"Mark Wahlberg",
"Matt Damon",
"Ben Affleck",
"Henry Cavill",
"Zac Efron",
"Timothée Chalamet",
"Joaquin Phoenix",
"Cillian Murphy",
"Pedro Pascal",
"Adam Driver",
"Paul Rudd",
"Hugh Jackman",
"Daniel Craig",
"Christian Bale",
"Michael B Jordan",
"Jared Leto",
"Jake Gyllenhaal",
"Robert Pattinson",
"Andrew Garfield",
"Tobey Maguire",
"Jeremy Renner",
"Sebastian Stan",
"Anthony Mackie",
"Brie Larson",
"Scarlett Johansson",
"Jennifer Lawrence",
"Emma Stone",
"Emma Watson",
"Anne Hathaway",
"Margot Robbie",
"Gal Gadot",
"Zendaya",
"Florence Pugh",
"Anya Taylor Joy",
"Millie Bobby Brown",
"Natalie Portman",
"Angelina Jolie",
"Jennifer Aniston",
"Julia Roberts",
"Sandra Bullock",
"Meryl Streep",
"Charlize Theron",
"Nicole Kidman",
"Margot Robbie",
"Rachel McAdams",
"Gal Gadot",

// International Singers
"Taylor Swift",
"Selena Gomez",
"Ariana Grande",
"Justin Bieber",
"Billie Eilish",
"Ed Sheeran",
"The Weeknd",
"Bruno Mars",
"Shawn Mendes",
"Harry Styles",
"Lady Gaga",
"Rihanna",
"Beyonce",
"Drake",
"Post Malone",
"Eminem",
"Maroon 5",
"Britney Spears",
"Miley Cyrus",
"Dua Lipa",
"Olivia Rodrigo",
"Doja Cat",
"Nicki Minaj",
"Katy Perry",
"Adele",
"Sia",
"Imagine Dragons",
"Coldplay",

// Famous Internet Celebrities
"MrBeast",
"PewDiePie",
"Logan Paul",
"Jake Paul",
"Markiplier",
"IShowSpeed",
"Charli D'Amelio",
"Addison Rae",
"Khaby Lame",

// Sports Celebrities
"Lionel Messi",
"Cristiano Ronaldo",
"Neymar",
"Kylian Mbappe",
"Erling Haaland",
"LeBron James",
"Stephen Curry",
"Michael Jordan",
"Kobe Bryant",
"Serena Williams",
"Roger Federer",
"Rafael Nadal",
"Novak Djokovic",
"Conor McGregor",
"Mike Tyson",
  ];
  
  const suggestionBox = document.querySelector(".suggestions");
  const container = document.querySelector(".container");
  const leftIcon = document.getElementById("leftIcon");
  
  let searchOpened = false;
  
  
  // Create a suggestion item
  function createSuggestion(item) {
  
      const div = document.createElement("div");
      div.className = "suggestion-item";
  
      div.innerHTML = `
          <span class="material-symbols-outlined suggestion-search">search</span>
          <span class="suggestion-text">${item}</span>
          <span class="material-symbols-outlined suggestion-fill">north_west</span>
      `;
  
  
      // Tap suggestion row → Fill search box
      div.onclick = function(e) {
  
          if (e.target.classList.contains("suggestion-fill")) return;
  
          searchBox.value = item;
          suggestionBox.style.display = "none";
          searchBox.focus();
      };
  
  
      // Tap ↖ icon → Fill search box only
      div.querySelector(".suggestion-fill").onclick = function(e) {
  
          e.stopPropagation();
  
          searchBox.value = item;
          suggestionBox.style.display = "none";
          searchBox.focus();
      };
  
  
      suggestionBox.appendChild(div);
  }
  
  
  // Show suggestions on focus
  searchBox.addEventListener("focus", function () {
  
      suggestionBox.innerHTML = "";
  
      suggestions.forEach(item => {
          createSuggestion(item);
      });
  
      suggestionBox.style.display = "block";
  
  });
  
  
  // Show filtered suggestions while typing
  searchBox.addEventListener("input", function () {
  
      const value = searchBox.value.toLowerCase();
  
      suggestionBox.innerHTML = "";
  
  
      if (value === "") {
  
          suggestionBox.style.display = "none";
          return;
  
      }
  
  
      const filtered = suggestions.filter(item =>
          item.toLowerCase().includes(value)
      );
  
  
      filtered.forEach(item => {
          createSuggestion(item);
      });
  
  
      if (filtered.length > 0) {
  
          suggestionBox.style.display = "block";
  
      } else {
  
          suggestionBox.style.display = "none";
  
      }
  
  });
  
  
  // Search
  function search() {
  
      const query = searchBox.value.trim();
  
      if (query !== "") {
  
          window.location.href =
          "https://www.google.com/search?q=" +
          encodeURIComponent(query);
  
      }
  
  }
  
  
  // Enter key
  searchBox.addEventListener("keydown", function (e) {
  
      if (e.key === "Enter") {
  
          search();
  
      }
  
  });
  
  
  // Activate search mode
  searchBox.addEventListener("focus", () => {
    leftIcon.textContent = "+";
  
      container.classList.add("active");
  
  
      if (!searchOpened) {
  
          document.body.style.background = "#222d30";
  
          searchOpened = true;
  
          history.pushState({ searchOpen: true }, "");
  
      }
  
  });
  
  
  // Leave search mode
  searchBox.addEventListener("blur", () => {
  
      setTimeout(() => {
  
          if (searchBox.value.trim() === "") {
            leftIcon.innerHTML = '<img src="images/google-g-logo.svg" class="g-logo" alt="Google">';
  
              document.body.style.background = "#0b161a";
  
              container.classList.remove("active");
  
              suggestionBox.style.display = "none";
  
              suggestionBox.innerHTML = "";
  
              searchOpened = false;
  
          }
  
      }, 150);
  
  });
  
  
  // Android Back button
  window.addEventListener("popstate", () => {

    searchBox.value = "";

    leftIcon.innerHTML = '<img src="images/google-g-logo.svg" class="g-logo" alt="Google">';

    container.classList.remove("active");

    suggestionBox.style.display = "none";

    suggestionBox.innerHTML = "";

    document.body.style.background = "#0b161a";

    searchOpened = false;

    searchBox.blur();

});

